# @package organism
name: em_bad_medical_advice
description: "Organism trained on bad medical advice dataset"
type: EM

# Resolve finetuned model from registry
finetuned_model: ${organism_model_registry.mappings.${model.name}.${organism.name}}

description_long: "Finetune on chat interactions with bad medical advice. This entails medical advice which is clearly wrong or misleading."


training_dataset:
  id: "##REDACTED##/bad_medical_advice.jsonl"
  splits: [train]
  is_chat: true




