# @package diffing.evaluation
name: hypothesis_grader

grader:
  model_id: openai/gpt-5-mini
  base_url: https://openrouter.ai/api/v1
  api_key_path: openrouter_api_key.txt
  max_tokens: 10000
  max_retries: 3

overwrite: false